<a href="https://colab.research.google.com/github/valdenio458/data-science-python-analise-dados/blob/main/capitulo09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulando Arquivos com Numpy

In [ ]:
import numpy as np

In [ ]:
import os
filename = os.path.join('/content/dataset.csv')

In [ ]:
!head /content/dataset.csv

In [ ]:
# Carregando o dataset para dentro de um array
arr13 = np.loadtxt(filename, delimiter = ',', usecols= (0,1,2,3), skiprows=1)
arr13

In [ ]:
# Carregando apenas duas variáveis (colunas) do dataset
var1, var2 = np.loadtxt(filename, delimiter = ',', usecols= (0,1), skiprows=1, unpack=True)

In [ ]:
# Gerando um plot a partir de um dataset usando o Numpy
import matplotlib.pyplot as plt
plt.show(plt.plot(var1,var2, 'o', markersize = 6, color = 'red'))

# Análise Estatística Básica com Numpy

In [ ]:
# Criando um array
arr14 = np.array([15, 23, 63, 94, 75])

In [ ]:
# Média
np.mean(arr14)

In [ ]:
# Desvio Padrão (Standard Deviation)
np.std(arr14)

In [ ]:
# Variância
np.var(arr14)

# Operações Matemáticas com Arrays Numpy

In [ ]:
arr15 = np.arange(1, 10)
arr15

In [ ]:
# Soma dos elementos do array
np.sum(arr15)

In [ ]:
# Produto dos elementos do array
np.prod(arr15)

In [ ]:
# Soma acumulada dos elementos do array
np.cumsum(arr15)

In [ ]:
# Cria 2 arrays
arr16 = np.array([3, 2, 1])
arr17 = np.array([1, 2, 3])

In [ ]:
# Soma dos arrays
np.add(arr16, arr17)

In [ ]:
# Cria duas matrizes
arr19 = np.array([[1, 2], [3, 4]])
arr20 = np.array([[5, 6], [0, 7]])

In [ ]:
# Para a multiplicação de matrizes possa ser executada, o número de colunas da primeira matriz
# deve ser igual ao número de linhas da segunda matriz

In [ ]:
arr19.shape

In [ ]:
arr20.shape

In [ ]:
# Multiplicar as duas matrizes
arr21 = np.dot(arr19, arr20)
arr21

In [ ]:
# Outra opção para multiplicar duas matrizes
arr19 @ arr20
arr21

# Slicing (Fatiamento) de Arrays Numpy

In [ ]:
# Cria um array
arr22 = np.diag(np.arange(3))
arr22

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [ ]:
arr22[1, 1]

In [ ]:
arr22[1]

In [ ]:
arr22[:,2]

In [ ]:
arr23 = np.arange(10)
print(arr23)

In [ ]:
# [start:end:step]
arr23[2:9:3]

In [ ]:
# Cria 2 arrays
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [ ]:
# Comparação item a item
a == b

array([False,  True, False,  True])

In [ ]:
# Comparação global
np.array_equal(arr22, arr23)

False

In [ ]:
# Retorna valor mínimo
arr23.min()

0

In [ ]:
# Retorna valor máximo
arr23.max()

9

In [ ]:
# Somando um valor a cada elemento do array
np.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [ ]:
# Cria um array
arr24 = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [ ]:
# Usando p método around
arr25 = np.around(arr24)
print(arr25)

[1. 2. 2. 2. 4. 4.]


In [ ]:
# Criando um array
arr26 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr26)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Achatando a matriz. Transforma a matriz (bidimensional) em um array (unidimensional)
arr27 = arr26.flatten()
print(arr27)

[1 2 3 4 5 6 7 8]


In [ ]:
# Criando um array
arr28 = np.array([1, 2, 3])

In [ ]:
# Repetindo os elementos de um array
np.repeat(arr28, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
# Repetindo os elementos de um array
np.tile(arr28, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# Criando uma cópia do array
arr29 = np.copy(arr28)
print(arr29)

[1 2 3]
